# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('travel', models.FloatField(blank=True, default=0, null=True, verbose_name='Travel')),
                ('food', models.FloatField(blank=True, default=0, null=True, verbose_name='Food')),
                ('miscellaneous', models.FloatField(blank=True, default=0, null=True, verbose_name='Miscellaneous')),
                ('descr', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Description')),
            ],
        ),
    ]
